### ISSUE TITLE
提交时候出现错误

### ISSUE THREAD

**Issue by ZCT** [ikitty/HerosData#4]
ERROR: Permission to ikitty/HerosData.git denied to ZCT

**Comment by ikitty** [comment]
弱问下，你是不是先fork到自己名下了，然后在自己分支commit的呢？

**Comment by ZCT** [comment]
额，我是clone 你这个git地址，修改后 再push的

**Comment by ZCT** [comment]
是不是应该先fork到自己名下，然后在自己分支commit，最后再pull request?  github不是太熟，多包涵哈~~

**Comment by ZCT** [comment]
嗯，明白了~~
