### ISSUE TITLE
没有逗号的地方用空格么？

### ISSUE THREAD

**Issue by cnluzhang** [ikitty/HerosData#7]
例如，第16位，职位分为两部分
例如，第17位，武器和必杀技都是空格隔开，没有逗号

如果是空格，是用两个字符的空格还是？

**Comment by ikitty** [comment]
你好，没有逗号，手动加一个逗号哈。（话说16和17的数据貌似都有了哦）. 
cnluzhang可以从风流威猛的金枪手开始补充哈。

**Comment by cnluzhang** [comment]
16/17的数据可是用空格了哦...没有用逗号，所以还是需要规范一下

**Comment by ikitty** [comment]
恩，后续我来调整一下。
