### ISSUE TITLE
使用认领的方式进行协作

### ISSUE THREAD

**Issue by 17** [ikitty/HerosData#8]
例如:

- [x] 1~5 已由 John Doe 完成
- [x] 5~10 已被 John Doe 承包
- [ ] 10~15 等待认领
- [x] 100~108 作者已完成

这样可以避免很多重复劳动和管理时间.

**Comment by ikitty** [comment]
Nice idea ， 这个checkbox是展示在github项目的说明文件中吗？

**Comment by 17** [comment]
恩, 一般放在 README.md. 每当浏览到这个项目都能知道进度, 也方便进行贡献.

**Comment by ikitty** [comment]
恩，已优化，多谢建议~
